service: ${self:custom.skillsmapper.name}-pipeline

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  skillsmapper: ${file(../skillsmapper.yml)}
  private: ${file(../private.yml)}
  events: ${file(../events.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.private.region}
  environment:
    NEO4J_URL: ${self:custom.private.neo4j-url}

functions:
  receiveEmail:
    handler: receiveEmail.receiveEmail
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":"
                - ${self:custom.skillsmapper.name}
                - "-"
                - ${self:custom.events.new-email}
          topicName: ${self:custom.skillsmapper.name}-${self:custom.events.new-email}
    environment:
      SNS_NEW_MESSAGE:
        Fn::Join:
          - ""
          - - "arn:aws:sns:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - ${self:custom.skillsmapper.name}
            - "-"
            - ${self:custom.events.message-received}
resources:
  Resources:
    NewEmail:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.skillsmapper.name}-${self:custom.events.new-email}
    MessageReceived:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.skillsmapper.name}-${self:custom.events.message-received}