service: ${self:custom.skillsmapper.name}-api

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  skillsmapper: ${file(../skillsmapper.yml)}
  private: ${file(../private.yml)}
  events: ${file(../events.yml)}
  resources: ${file(../resources.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${self:custom.private.region}
  environment:
    NEO4J_URL: ${self:custom.private.neo4j-url}
    DEFAULT_PHOTO_URL: ${self:custom.resources.default-photo-url}

functions:
  getAllPeople:
    handler: getAllPeople.getAllPeople
    events:
      - http:
          path: profiles
          method: get
          cors: true
  getProfile:
    handler: getProfile.getProfile
    environment:
      SNS_NO_PHOTO:
        Fn::Join:
          - ""
          - - "arn:aws:sns:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - ${self:custom.skillsmapper.name}
            - "-"
            - ${self:custom.events.no-photo-found}
    events:
      - http:
          path: profile
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                email: false
                hash: false
  getProfileSkills:
    handler: getProfileSkills.getProfileSkills
    events:
      - http:
          path: profile/skills
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                email: false
                hash: false
  getAllSkills:
    handler: getAllSkills.getAllSkills
    events:
      - http:
          path: skills
          method: get
          cors: true
  getSkill:
    handler: getSkill.getSkill
    events:
      - http:
          path: skills/{tag}
          method: get
          cors: true
          request:
            parameters:
              paths:
                tag: true
  getSkillDescription:
    handler: getSkillDescription.getSkillDescription
    environment:
      SNS_NO_DESCRIPTION:
        Fn::Join:
          - ""
          - - "arn:aws:sns:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - ${self:custom.skillsmapper.name}
            - "-"
            - ${self:custom.events.no-description-found}
    events:
      - http:
          path: skills/{tag}/description
          method: get
          cors: true
          request:
            parameters:
              paths:
                tag: true

